flowchart LR
    student_dest["学生视图"]
    student["学生"]
    Class["班级"]
    teacher["老师"]
    calendar["日程表"]
    todotab["代办栏"]
    msgbox["通知箱"]
    storage[("数据存储")]
    event_center(["接收事务"])

    event_center -->|"学生课程"| calendar
    event_center -->|"班级会议"| calendar
    event_center -->|"学生代办"| todotab
    event_center -->|"班级作业"| todotab
    event_center -->|"班级通知"| msgbox
    
    calendar -->|"风格化展示"| student_dest
    todotab -->|"列表化展示"| student_dest
    msgbox -->|"列表化展示"| student_dest

    student -->|"学生事务"| event_center
    event_center -.-> storage
    
    teacher -->|"班级事务"| Class -->|"班级事务"| event_center
    