flowchart LR
    subgraph TeacherSys["教师通知分发系统"]
        direction LR

        Teacher["教师"]
        Class["班级"]
        MsgEditing("4.1 编辑通知")
        MsgDistribute("4.2 通知分发")
        MsgDb[("通知存储")]
        StuDummy1["学生通知箱"]
        StuDummy2["学生通知箱"]
        StuDummy3["学生通知箱"]

        Teacher -->|"通知草稿"| MsgEditing -->|"通知"| Class -->|"通知"| MsgDistribute
        MsgEditing -->|"更新后通知草稿"| MsgEditing

        Class <-.-> MsgDb
        MsgEditing <-.-> MsgDb

        MsgDistribute --> StuDummy1
        MsgDistribute --> StuDummy2
        MsgDistribute --> StuDummy3
    end


    subgraph StudentSys["学生事务管理系统"]
        direction TB
        
        subgraph EventSys["事件管理"]
            direction LR

            StudentEventSys["学生"]
            StudentViewEventSys["学生视图"]
            EventView["2.5 事件表"]
            EventAdd("2.1 添加事件")
            EventDel("2.2 删除事件")
            EventMod("2.3 修改事件")
            EventDB[("事件存储")]
            MsgViewEventSys["通知箱"]
            IntoEvent("2.4 转换为事件")

            StudentEventSys -->|"事件"| EventAdd
            StudentEventSys -->|"删除请求"| EventDel
            StudentEventSys -->|"修改请求"| EventMod

            EventAdd -->|"更新后事件表"| EventView
            EventMod -->|"更新后事件表"| EventView
            EventDel -->|"更新后事件表"| EventView

            MsgViewEventSys -->|"通知信息"| IntoEvent
            IntoEvent -->|"更新后事件表"| EventView

            EventView -->|"事件表"| StudentViewEventSys

            EventAdd -.-> EventDB
            EventMod -.-> EventDB
            EventDel -.-> EventDB
            IntoEvent -.-> EventDB
            EventDB -.-> EventView

        end

        subgraph TodoSys["待办管理"]
            direction LR

            StudentTodoSys["学生"]
            TodoView["2.10 待办栏"]
            StudentViewTodoSys["学生视图"]
            MsgViewTodoSys["通知箱"]
            TodoAdd["2.6 添加待办"]
            TodoDel["2.7 删除待办"]
            TodoMod["2.8 修改待办"]
            TodoDB[("待办存储")]
            IntoTodo("2.9 转换为待办")
            
            TodoAdd -->|"更新后待办栏"| TodoView
            TodoDel -->|"更新后待办栏"| TodoView
            TodoMod -->|"更新后待办栏"| TodoView

            MsgViewTodoSys -->|"通知信息"| IntoTodo
            IntoTodo -->|"更新后待办栏"| TodoView

            TodoView -->|"待办栏"| StudentViewTodoSys

            StudentTodoSys -->|"待办"| TodoAdd
            StudentTodoSys -->|"删除请求"| TodoDel
            StudentTodoSys -->|"修改请求"| TodoMod
            
            TodoAdd -.-> TodoDB
            TodoDel -.-> TodoDB
            TodoMod -.-> TodoDB
            IntoTodo -.-> TodoDB
            TodoDB -.-> TodoView

            TodoView
        end
    end

    subgraph ClassSys["班级管理系统"]
        direction LR

        StudentClassSys["学生"]
        TeacherClassSys["教师"]
        ApprovalSys("3.1 申请处理")
        ClassDB[("班级存储")]

        StudentClassSys -->|"入班申请"| ApprovalSys
        TeacherClassSys -->|"添加班级申请"| ApprovalSys
        TeacherClassSys -->|"加入学生申请"| ApprovalSys
        ApprovalSys <-.-> ClassDB
    end

    subgraph LoginSys["登录管理系统"]
        direction LR

        User["用户"]
        Login("1.1 登录")
        Signup("1.2 注册")
        StuUser["学生用户"]
        TchUser["教师用户"]

        UserDB[("用户数据库")]

        User -->|"登录信息"| Login
        User -->|"注册信息"| Signup

        Login --->|"学生信息"| StuUser
        Login --->|"教师信息"| TchUser

        Signup -.->|"注册信息"| UserDB
        UserDB -.->|"身份信息"| Signup

        Login -.->|"登录信息"| UserDB
        UserDB -.->|"用户信息"| Login
    end
