stateDiagram-v2
direction LR
    [*] --> 学生系统

    state ChooseTab <<fork>>
    学生系统 --> ChooseTab: 选择标签页
    ChooseTab --> 事件管理
    ChooseTab --> 代办管理
    ChooseTab --> 通知管理
    ChooseTab --> 个人信息管理


    state 事件管理 {
        direction LR
        
        [*] --> 阅览事件
        阅览事件 --> [*]
        阅览事件 --> 查看事件细节: 选中事件
        查看事件细节 --> [*]
        查看事件细节 --> 编辑事件细节: 选择编辑事件
        编辑事件细节 --> [*]
    }

    state 代办管理 {
        direction LR
        
        [*] --> 阅览代办
        阅览代办 --> [*]
        阅览代办 --> 等待输入代办细节: 选择添加代办
        等待输入代办细节 --> 完成添加代办: 输入细节
        完成添加代办 --> [*]
        阅览代办 --> 查看代办细节: 选中代办
        查看代办细节 --> [*]
        查看代办细节 --> 编辑代办: 选择编辑
        编辑代办 --> 完成编辑代办: 更新细节
        查看代办细节 --> 删除代办: 选择删除
        删除代办 --> [*]
        完成编辑代办 --> [*]
    }

    state 通知管理 {
        direction LR
        
        [*] --> 阅览通知
        阅览通知 --> [*]
        阅览通知 --> 等待输入通知细节: 选择添加通知
        等待输入通知细节 --> 完成添加通知: 输入细节
        完成添加通知 --> [*]
        阅览通知 --> 查看通知细节: 选中通知
        查看通知细节 --> [*]
        查看通知细节 --> 编辑通知: 选择编辑
        编辑通知 --> 完成编辑通知: 更新细节
        查看通知细节 --> 删除通知: 选择删除
        删除通知 --> [*]
        完成编辑通知 --> [*]
        查看通知细节 --> 编辑为事件: 选择转换为事件
        查看通知细节 --> 编辑为代办: 选择转换为代办
        编辑为事件 --> [*]
        编辑为代办 --> [*]
    }

    state 个人信息管理 {
        direction LR

        [*] --> 查看个人信息
        查看个人信息 --> [*]
        查看个人信息 --> 编辑个人信息: 选择编辑个人信息
        编辑个人信息 --> [*]
        [*] --> 查看班级信息
        查看班级信息 --> 等待输入班级号: 选择加入班级
        等待输入班级号 --> 成功加入班级: 合法请求
        等待输入班级号 --> 加入班级失败: 非法请求
        查看班级信息 --> 离开班级: 选择离开选中班级
        成功加入班级 --> [*]
        加入班级失败 --> [*]
        离开班级 --> [*]
    }

    state FinalBranch <<choice>>

    FinalBranch --> ChooseTab: 切换标签页
    FinalBranch --> [*]: 退出系统

    事件管理 --> FinalBranch
    代办管理 --> FinalBranch
    通知管理 --> FinalBranch
    个人信息管理 --> FinalBranch
