stateDiagram-v2
direction LR
    [*] --> 老师界面

    老师界面 --> 选择班级
    老师界面 --> 添加班级

    state choose_tab <<choice>>
    选择班级 --> choose_tab: 选择界面
    choose_tab --> 学生管理
    choose_tab --> 作业管理
    choose_tab --> 通知管理

    学生管理 --> 添加学生
    学生管理 --> 移除学生

    作业管理 --> 新建作业草稿
    新建作业草稿 --> 编辑作业草稿
    编辑作业草稿 --> 编辑作业草稿
    编辑作业草稿 --> 发布作业

    作业管理 --> 查看作业完成情况

    通知管理 --> 新建通知草稿
    新建通知草稿 --> 编辑通知草稿
    编辑通知草稿 --> 编辑通知草稿
    编辑通知草稿 --> 发布通知